name: Test
on: push
#on:
#  push
#workflow_run:
#workflows: [ValidatePipeline]
#types: [completed]

jobs:
  use-minimal:
    uses: ./.github/workflows/minreuseflow.yaml
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Output event data
        run: echo "${{ toJSON(github.event) }}"
      - name: Get code
        uses: actions/checkout@v3
      - name: Cache dependencies
        uses: actions/cache@v3 ##T get list of all the actions https://github.com/actions/cache
        with:
          path: ~/.npm ##This is the path to cache the npm dependencies, the dependencies are stored in the ~/.npm directory
          key: depend-node-modules-${{hashFiles('**/package-lock.json')}}
      - name: Install dependencies
        run: npm ci
      - name: Test code
        run: npm run test
      - name: Build code
        run: npm run build
      - name: Deploy project
        run: echo "Deploying..."

  deploy:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Output events data ## This step outputs the event data
        run: echo "${{ toJSON(github.event) }}"
      - name: Get code
        uses: actions/checkout@v3
      - name: Cache dependencies
        uses: actions/cache@v3 ##To get list of all the actions https://github.com/actions/cache
        with:
          path: ~/.npm
          key: depend-node-modules-${{hashFiles('**/package-lock.json')}}
      - name: Install dependencies
        run: npm ci
      - name: Test code
        run: npm run test
        if: steps.cache.outputs.cache-hit != 'true' ## This step will only run if the cache is not hit, meaning the dependencies are not cached
      - name: Build code
        run: npm run build
      - name: Deploy project
        run: echo "Deploying..." ### This step simulates deployment

