##https://github.com/actions/cache
###https://github.com/marketplace/actions/setup-github-cli
name: cache
on: workflow_dispatch

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Get code
        uses: actions/checkout@v3
      # Add caching
      - name: Cache dependencies
        id: cache
        uses: action/cache@v4
        with:
           path: node_modules
           key: deps-node-modules-${{ hashFiles('**/package-lock.json') }}
      - name: Install dependencies
        if: steps.cache.outputs.cache-hit != 'true'
        ## format for chceking and calling cache: steps.<step_id>.outputs.<output_name>
        run: npm ci
      - name: Test code
        run: npm run test
      - run: npm run build

  clear:
    runs-on: ubuntu-latest
    needs: test
    permissions:
      actions: write
    steps:
      - uses: sersoft-gmbh/setup-gh-cli-action@v2
      - name: Delete branch‑specific caches
        env:
          GH_TOKEN: ${{ secrets.PAT_TOKEN }}  # Must have repo scope
        run: |
          gh cache list \
            --repo "${{ github.repository }}" \
            --ref "refs/heads/${{ github.ref_name }}" \
            --limit 100 --json id --jq '.[].id' \
          | while read cacheId; do
              gh cache delete "$cacheId" --repo "${{ github.repository }}"
            done