name: cache
on: push

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      # Add caching
      - run: npm ci
      - run: npm run build

  clear:
    runs-on: ubuntu-latest
    needs: test
    permissions:
      actions: write
    steps:
      - uses: sersoft-gmbh/setup-gh-cli-action@v2
      - name: Delete branch-specific caches
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh cache list \
              --repo "RohiniGajakosh/gitflow" \
              --ref "refs/heads/rohini" \
              --limit 100 \
              --json id --jq '.[].id' \
              | while read cacheId; do
                echo "Deleting cache ID $cacheId"
                gh cache delete "$cacheId" --repo "RohiniGajakosh/gitflow" --confirm
              done