name: ai
on: push

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "20.19.0"

      - name: Cache node_modules
        id: node_modules-cache
        uses: actions/cache@v3
        with:
          path: node_modules
          key: ${{ runner.os }}-node-modules-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-modules-
        ## This key is based on the OS and the hash of package-lock.json
        ## It allows restoring the cache across different runs and OS types
        ## If the cache is not found, it will create a new one with the same key

      - name: Show cache status
        run: echo "Cache hit ${{ steps.node_modules-cache.outputs.cache-hit }}"

      - name: Install dependencies
        if: steps.node_modules-cache.outputs.cache-hit != 'true'
        run: npm ci

      # ✅ FIX 1: Restore execute permission to esbuild binary if it exists
      - name: Fix esbuild permissions (before install)
        if: steps.node_modules-cache.outputs.cache-hit == 'true'
        run: |
          if [ -f node_modules/esbuild/bin/esbuild ]; then
            echo "Fixing permissions on esbuild binary"
            chmod +x node_modules/esbuild/bin/esbuild
          fi

      - name: Install dependencies
        run: npm ci

      - name: Run tests
        run: npm run test

      - name: Build
        run: npm run build

      # ✅ FIX 2: Upload node_modules only if cache miss (to share with other jobs)
      - name: Save node_modules as artifact
        if: steps.node_modules-cache.outputs.cache-hit != 'true'
        uses: actions/upload-artifact@v4
        with:
          name: node_modules
          path: node_modules/

  test-again:
    runs-on: ubuntu-latest
    needs: build-and-test
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: "20.19.0"

      # ✅ FIX 3: Restore previously uploaded node_modules
      - name: Download node_modules artifact
        uses: actions/download-artifact@v4
        with:
          name: node_modules
          path: node_modules/

      # ✅ FIX 4: Fix permission again after artifact restore
      - name: Fix esbuild permissions (after artifact restore)
        run: |
          echo "Fixing all esbuild binary permissions recursively..."
          find node_modules -type f -name "esbuild" -exec chmod +x {} \;
          if [ -f node_modules/esbuild/bin/esbuild ]; then
            chmod +x node_modules/esbuild/bin/esbuild
          fi
      - name: Show permission after chmod
        run: ls -l node_modules/esbuild/bin/esbuild || true

      - name: Install Vitest and run additional tests
        run: |
          npm install --save-dev vitest --loglevel verbose
          npm run test

  clear-cache:
    runs-on: ubuntu-latest
    needs: [build-and-test, test-again]
    if: always()
    permissions:
      actions: write
    steps:
      - name: Setup GitHub CLI
        uses: sersoft-gmbh/setup-gh-cli-action@v2

      - name: Delete branch-specific caches
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          echo "Fetching cache IDs for branch: ${{ github.ref_name }}"
          CACHE_IDS=$(gh cache list \
            --repo "${{ github.repository }}" \
            --ref "refs/heads/${{ github.ref_name }}" \
            --limit 100 --json id --jq '.[].id')

          if [ -z "$CACHE_IDS" ]; then
            echo " No caches found for branch: ${{ github.ref_name }}"
          else
            echo " Found cache IDs:"
            echo "$CACHE_IDS"
            echo "$CACHE_IDS" | while read cacheId; do
              echo " Deleting cache ID $cacheId"
              gh cache delete "$cacheId" --repo "${{ github.repository }}"
            done
          fi

  report:
    runs-on: ubuntu-latest
    needs: [build-and-test, test-again, clear-cache]
    if: failure()
    steps:
      - name: Output debug info
        run: |
          echo " Workflow failed"
          echo "${{ toJSON(github) }}"
