##https://docs.github.com/en/actions/reference/workflows-and-actions/contexts#context-availability
name: Website Deployment
on: workflow_dispatch
#on:
#  push
# branches:
#   - main
#   - master
#   - raj
#   - rohini
jobs:
  lint:
    runs-on: ubuntu-latest
    continue-on-error: true ## This job will continue even if it fails, useful for testing purposes
    steps:
      - name: Get code
        uses: actions/checkout@v4
      - name: Cache dependencies
        id: cache
        uses: actions/cache@v3
        with:
          path: ~/.npm ## This is the path to cache the npm dependencies, the dependencies are stored in the ~/.npm directory
          key: deps-node-modules-${{ hashFiles('**/package-lock.json') }}
      - name: Install dependencies
        if: steps.cache.outputs.cache-hit != 'true' ## This step will only run if the cache is not hit, meaning the dependencies are not cached
        run: npm ci
      - name: Lint code
        run: npm run lint
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Get code
        uses: actions/checkout@v4
      - name: Install dependencies
        run: npm ci
      - name: Test code
        id: run-tests
        run: npm run test
      - name: Upload test report
        if: failure() && steps.run-tests.outcome == 'failure' ## This step is condition for next step only runs if this step fails   ###https://docs.github.com/en/actions/reference/contexts-reference all the refrence contexts and syntax can be found here
        ##faliure() always returns true if any job or functions fails, or previous step fails, sucess() reuts true when none of the previous step fails, always() returns true no matter what the previous step returns, cancelled() retuns true when the workflow is cancelled, success() returns true when the previous step is successful
        uses: actions/upload-artifact@v4
        with:
          name: test-report
          path: test.json
      - name: Upload test report on failure only
        if: ${{ failure() && steps.run-tests.outcome == 'failure' }}
        uses: actions/upload-artifact@v4
        with:
          name: test-report
          path: test.json

  build:
    needs: [lint, test] ## This job depends on the lint and test jobs, it will only run if both jobs are successful
    if: ${{ needs.lint.result == 'success' && needs.test.result == 'success' }} ## This job will only run if the lint and test jobs are successful
    runs-on: ubuntu-latest
    steps:
      - name: Get code
        uses: actions/checkout@v4
      - name: Install dependencies
        run: npm ci
      - name: Build website
        id: build-website
        run: npm run build
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: dist-files
          path: dist
  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Get build artifacts
        uses: actions/download-artifact@v4
        with:
          name: dist-files
      - name: Output contents
        run: ls
      - name: Deploy
        run: echo "Deploying..."
  report:
   needs: [lint, test, build, deploy]
   # run no matter what, then branch per-step
   if: ${{ always() }}
   runs-on: ubuntu-latest
   steps:
   - name: Success summary
     if: ${{ needs.lint.result == 'success' &&
             needs.test.result == 'success' &&
             needs.build.result == 'success' &&
             needs.deploy.result == 'success' }}
     run: echo "All jobs completed successfully."
   - name: Failure summary
     # any upstream failure OR cancelled
     if: ${{ contains(join(needs.*.result, ','), 'failure') ||
             contains(join(needs.*.result, ','), 'cancelled') }}
     run: |
       echo "One or more jobs failed or were cancelled."
       echo "lint=${{ needs.lint.result }}"
       echo "test=${{ needs.test.result }}"
       echo "build=${{ needs.build.result }}"
       echo "deploy=${{ needs.deploy.result }}"