name: Matrix Example

on: push

jobs:
  build:
    continue-on-error: true ## This step will continue even if it fails, useful for testing purposes at job level, makes the entire job continue even if one step fails
    strategy: ## This is used to define a matrix of jobs, allowing the same job to
      fail-fast: false ## This option allows the matrix to continue running even if one of the jobs fails
      max-parallel: 2 ## This option allows to limit the number of jobs that can run in parallel
      matrix: ## This is used to define a matrix of jobs, allowing the same job to run on multiple configurations
        os: [ubuntu-latest, windows-latest] ## Define the OS matrix
        python: [3.9, 3.10, 3.11, 3.12] # Define the versions of Node.js to test against
        include: ## This is used to include additional configurations in the matrix
          - python: 3.11 ## This is the Node.js version to test against
            os: ubuntu-latest
          - python: 3.10 ## This is the Node.js version to test against
            os: windows-latest
        exclude: ## This is used to exclude configurations from the matrix
          - python: 3.9 ## This is the Node.js version to exclude
            os: windows-latest ## This is the operating system to exclude
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          python: ${{ matrix.python }}
      - name: Install dependencies
        run: npm install
      - name: Run tests
        run: npm test
