name: CI/CD Pipeline
on:
  push:
    branches:
      - master
      - main
jobs:
  checkout:
    name: Checkout code
    runs-on: ubuntu-latest
    steps:
      - name: Output event data
        run: echo "${{ toJSON(github.event) }}" ### This step outputs the event data
      - name: Get code
        uses: actions/checkout@v3
  setup:
    name: Setup Environment
    needs: checkout
    runs-on: ubuntu-latest
    steps:
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: "18"
  install:
    name: Install Dependencies
    needs: setup
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: npm ci

  test:
    name: Run Tests
    needs: install
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install dependencies
        run: npm install
      - name: Install Vitest
        run: npm install --save-dev vitest
      - name: Run unit tests
        run: npm run test
      - name: Run integration tests
        run: npm run test:integration
      - name: Run e2e tests
        run: npm run test

  build:
    name: Build App
    needs: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: npm run build

  package:
    name: Package App
    needs: build
    runs-on: ubuntu-latest
    steps:
      - run: echo "Packaging build artifacts..."

  upload-artifacts:
    name: Upload Artifacts
    needs: package
    runs-on: ubuntu-latest
    steps:
      - uses: actions/upload-artifact@v3
        with:
          name: build-artifacts
          path: ./dist

  deploy-staging:
    name: Deploy to Staging
    needs: upload-artifacts
    runs-on: ubuntu-latest
    steps:
      - run: echo "Deploying to staging..."

  approval:
    name: Await Manual Approval
    needs: deploy-staging
    runs-on: ubuntu-latest
    environment:
      name: production
      url: https://your-production-site.com
    steps:
      - name: Wait for approval
        run: echo "Waiting for manual approval..."

  deploy-prod:
    name: Deploy to Production
    needs: approval
    runs-on: ubuntu-latest
    steps:
      - run: echo "Deploying to production..."
